### ISSUE TITLE
Cookie consent

### ISSUE THREAD

**Issue by zeekay** [hanzoai/react-sdk#74]
Ensure we are collecting cookie consent and signaling support appropriately https://developers.facebook.com/docs/app-events/cookies

**Comment by artemis-prime** [comment]
@zeekay , please move this to the other repo

**Comment by zeekay** [comment]
Where is analytics support in Hanzo? It should be built in to our UI library.

**Comment by artemis-prime** [comment]
Right but we decided to file all bugs in the other repo regardless, remember?
